todo:
    autoAssign: true
    keyword: ['@todo', 'TODO', 'todo']
    bodyKeyword: ['@body', 'BODY', 'body']
    blobLines: 10
    caseSensitive: false
    label: true
    reopenClosed: true
    exclude: null
